### ISSUE TITLE
Θέμα λογική στο https://localhost:4015/api/Incidents

### ISSUE THREAD

**Issue by ndis** [spiroan2012/SmartAlertBackEnd#2]
Οταν γιδοβοσκός αναφέρει για νιοστή φορά περιστατικό:
1) στην ίδια κατηγορίας
2) εντός της ακτίνας του major incident
3) εντός του χρονικού ορίου

Εμείς πρέπει να το μετράμε σαν μονάδα.

**Comment by spiroan2012** [comment]
Completed
