### ISSUE TITLE
PATCH Αίτημα για αλλαγή κατάστασης ενός Master Incident

### ISSUE THREAD

**Issue by ndis** [spiroan2012/SmartAlertBackEnd#8]
Να εμπλουτιστεί και με ορισμένα επιπλέον στοιχεία όπως το  id χρήστη και τον χρόνο του αιτήματος

**Comment by spiroan2012** [comment]
Ο χρόνος του αιτήματος υπήρχε ήδη (πίνακας Incidents => StatusChangeDateTime). Προστέθηκε καιτ το πεδίο StatusChangeUid. Το request για το patch έχει την παρακάτω μορφή:

{
    "IncidentId": 18,
    "Status": 2,
    "uid": "bFG2B19DerOgNblIXHm3jWu4w45BC3"
}
